app:
    resource: "@AppBundle/Controller/"
    type:     annotation
movements:
    type:     rest
    resource: AppBundle\Controller\MovementsController
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc