# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
imports:
  - { resource: @AppBundle/Resources/Services/infrastructure-services.yml }
  - { resource: @AppBundle/Resources/Services/domain-services.yml }
  - { resource: @AppBundle/Resources/Services/interactors-services.yml }