Kontuak\PeriodicalMovement:
    type: entity
    table: movements
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        amount:
            type: float
        concept:
            type: text
        periodType:
            type: integer
        periodAmount:
            type: integer
        starts:
            type: date
        ends:
            type: date
            nullable: true
        created:
            type: datetime
        modified:
            type: datetime